# -*- coding: utf-8 -*-
{
    'name': "supermodulo16",

    'summary': """
        Short (1 phrase/line) summary of the module's purpose, used as
        subtitle on modules listing or apps.openerp.com""",

    'description': """
        Long description of module's purpose
    """,

    'author': "My Company",
    'website': "https://www.yourcompany.com",

    # Categories can be used to filter modules in modules listing
    # Check https://github.com/odoo/odoo/blob/16.0/odoo/addons/base/data/ir_module_category_data.xml
    # for the full list
    'category': 'Uncategorized',
    'version': '0.1',

    # any module necessary for this one to work correctly
    'depends':[
'account_asset_management',
'account_banking_mandate',
'account_chart_update',
'account_due_list',
'account_edi_ubl_cii',
'account_edi',
'account_financial_report',
'account_invoice_overdue_reminder',
'account_invoice_refund_link',
'account_lock_date_update',
'account_move_name_sequence',
'account_payment_invoice_online_payment_patch',
'account_payment_mode',
'account_payment_order',
'account_payment_partner',
'account_payment_sale',
'account_payment_term_extension',
'account_payment',
'account_qr_code_sepa',
'account_reconcile_oca',
'account_sequence',
'account_statement_base',
'account_statement_import_base',
'account_statement_import_file',
'account_tax_balance',
'account',
'analytic',
'auth_signup',
'auth_totp_mail',
'auth_totp_portal',
'auth_totp',
'auto_backup',
'barcodes_gs1_nomenclature',
'barcodes',
'base_address_extended',
'base_bank_from_iban',
'base_iban',
'base_import',
'base_install_request',
'base_location_geonames_import',
'base_location',
'base_partner_sequence',
'base_setup',
'base_sparse_field',
'base_technical_features',
'base_vat',
'base',
'board',
'bus',
'calendar_sms',
'calendar',
'contacts',
'contract',
'crm_iap_enrich',
'crm_iap_mine',
'crm_sms',
'crm',
'date_range_account',
'date_range',
'digest',
'disable_odoo_online',
'document_knowledge',
'document_page_approval',
'document_page_group',
'document_page_tag',
'document_page',
'document_url',
'gamification_sale_crm',
'gamification',
'google_gmail',
'hr_attendance',
'hr_contract',
'hr_expense',
'hr_gamification',
'hr_holidays_attendance',
'hr_holidays',
'hr_org_chart',
'hr',
'http_routing',
'iap_crm',
'iap_mail',
'iap',
'l10n_es_account_asset',
'l10n_es_account_statement_import_n43',
'l10n_es_aeat_mod115',
'l10n_es_aeat_mod123',
'l10n_es_aeat_mod303',
'l10n_es_aeat_mod347',
'l10n_es_aeat_mod349',
'l10n_es_aeat_mod390',
'l10n_es_aeat_partner_check',
'l10n_es_aeat',
'l10n_es_dua',
'l10n_es_mis_report',
'l10n_es_partner',
'l10n_es_toponyms',
'l10n_es_vat_book',
'l10n_es',
'link_tracker',
'login_user_detail',
'mail_bot_hr',
'mail_bot',
'mail',
'mass_mailing_crm',
'mass_mailing_sale',
'mass_mailing_themes',
'mass_mailing',
'mis_builder_budget',
'mis_builder',
'mrp_account',
'mrp',
'note',
'partner_autocomplete',
'partner_manual_rank',
'payment',
'phone_validation',
'portal_rating',
'portal',
'privacy_lookup',
'product',
'project_hr_expense',
'project_mrp',
'project_purchase',
'project_sale_expense',
'project_sms',
'project_task_add_very_high',
'project_task_default_stage',
'project_timeline',
'project',
'purchase_mrp',
'purchase_price_diff',
'purchase_stock',
'purchase',
'rating',
'remove_odoo_enterprise',
'report_xlsx_helper',
'report_xlsx',
'resource',
'sale_crm',
'sale_expense',
'sale_management',
'sale_mrp',
'sale_product_configurator',
'sale_product_template_tags',
'sale_project_stock',
'sale_project',
'sale_purchase_stock',
'sale_purchase',
'sale_sms',
'sale_stock',
'sale',
'sales_team',
'show_db_name',
'sms',
'snailmail_account',
'snailmail',
'social_media',
'spreadsheet_account',
'spreadsheet_dashboard_account',
'spreadsheet_dashboard_hr_expense',
'spreadsheet_dashboard_purchase_stock',
'spreadsheet_dashboard_purchase',
'spreadsheet_dashboard_sale_expense',
'spreadsheet_dashboard_sale',
'spreadsheet_dashboard_stock_account',
'spreadsheet_dashboard',
'spreadsheet',
'stock_account',
'stock_sms',
'stock',
'survey',
'uom',
'utm',
'web_chatter_position',
'web_editor',
'web_kanban_gauge',
'web_no_bubble',
'web_responsive',
'web_timeline',
'web_tour',
'web_unsplash',
'web',
'account_move_line_reconcile_manual',
'server_action_mass_edit',
'account_invoice_line_report',
'account_netting',
    
    ],
    # always loaded
    'data': [
        # 'security/ir.model.access.csv',
        'views/views.xml',
        'views/templates.xml',
    ],
    # only loaded in demonstration mode
    'demo': [
        'demo/demo.xml',
    ],
}
